### ISSUE TITLE
Question regarding lifecycles

### ISSUE THREAD

**Issue by Dragas** [greysonp/permiso#20]
In FAQ you mention that I can call `permisoInstance.setActivity(this)` so that I wouldn't have to extend PermisoActivity.
What about unregistering `this` activity? There doesn't seem to be a method for that. How come? Is it already handled by Permiso?

**Comment by greysonp** [comment]
Hi! If you want to "deregister" the activity, you can simply call `setActivity(null)`. However, Permiso only holds a weak reference to the activity, so it'll never prevent your activity from being garbage collected, so practically you should never really have to do that. That's why the param is marked `@NonNull` - I figured it'd help keep people out of trouble. Of course it's just an annotation and won't keep you from compiling, so feel free to ignore it :)
