### ISSUE TITLE
Custom PermisoDialogFragment.IOnCloseListener for "Permanently Denied"

### ISSUE THREAD

**Issue by phileo** [greysonp/permiso#28]
Inside `Permiso.IOnPermissionResult.onPermissionResult()` I can know whether a permission has been permanently denied.  If it has been perm. denied, I don't want to leave the user high and dry.  Instead I would like to show a dialog to point them towards a possible corrective action (eg. Settings screen where they can enable the permissions that I need).

So for the above use case, I could create my own dialog fragment to handle this, but PermisoDialogFragment can do all of this for me already if I could call like so:
`Permiso.getInstance().showRationaleInDialog(getBuilder(getPermDeniedData()), 
                permDeniedListener,
                rationaleCallback);`

`PermisoDialogFragment.IOnCloseListener` would need to define `onCancel()` as well.
Is there any appetite for this change?
If so I can make a pull request

**Comment by greysonp** [comment]
Just to get some clarification, is the end goal that you want to display a dialog fragment when a permission has been permanently denied that allows you to direct the user to the settings? 

If so, I think that goes beyond the intent of ```showRationaleInDialog()```, which was just intended to show the rationale after a denial. It's also very much tied to the lifecycle of asking for a rationale, which is why it's in a separate callback (```onRationaleRequested()```) and why ```showRationaleInDialog()``` requires an ```IOnRationaleProvided``` - so it can continue the permission request afterwards.

Meanwhile, you find out if a permission was permanently denied in the ```onPermissionResult()``` callback, which doesn't have the ```IOnRationaleProvided```, meaning we can't even use ```showRationaleInDialog()``` if we wanted to.

So, I think your best bet is to just show your own dialog fragment the normal way. If you want, you can subclass ```PermisoDialogFragment``` to start, but honestly the class does very little and is mostly there for convenience. I suppose we could add some other method for showing this permanently denied dialog? What do you think?
