### ISSUE TITLE
Reduce minimum SDK version to 14

### ISSUE THREAD

**Issue by akhy** [greysonp/permiso#3]
Why the minimum version is 16? Is there any specific feature that can only be implemented in v16+?

Would love to use this lib with minimum SDK version 14.

**Comment by greysonp** [comment]
You're right, I feel like I just chose 16 because that's the default for new projects, and I haven't had time to do extensive testing on earlier versions. I'm going to be busy with holiday stuff until Sunday. If you wanted to make a PR before then, I wouldn't complain ;) Otherwise I'll get to it then!
