### ISSUE TITLE
Failed to resolve: com.greysonparrelli.permiso:permiso:0.1.3

### ISSUE THREAD

**Issue by biovolt** [greysonp/permiso#8]
compile 'com.greysonparrelli.permiso:permiso:0.1.3' give me the following error.
**Error:Failed to resolve: com.greysonparrelli.permiso:permiso:0.1.3**

However 
compile 'com.greysonparrelli.permiso:permiso:**+**' 
Manage to compile version **0.1.0** however this version requires minSdkVersion to be 16

Is there a setting missing?

**Comment by greysonp** [comment]
Hey, you're not crazy, I had something similar happen to me when I was using permiso in a side project. I was getting this error when I knew very well that this version existed.

For me, it happened when I was using a preview build of Android Studio 2.0 in a new project. The templates for new projects were broken in that build of Android Studio, and me fixing my gradle plugin version created some weird set of conditions where this happened. I couldn't tell you the exact issue, because I ended up solving it by doing some number of cleans and building from the command line, ignoring Android Studio all together.

So try that: do a `./gradlew clean` followed by a `./gradlew assembleDebug` from the command line and let me know if it builds. 

If that doesn't work, make sure Android Studio is up to date and then create a new project that just imports permiso. If that still breaks, then maybe something else is going on.

**Comment by greysonp** [comment]
Oh, I guess I should also mention that you need to have the following snippet in your `build.gradle`:

``` groovy
repositories {
    jcenter()
}
```

This is in all new projects by default already, so it's very unlikely that you don't have it, but maybe you changed something.

You can see a full example of a `build.gradle` [here](https://github.com/greysonp/permiso/blob/master/build.gradle).

**Comment by biovolt** [comment]
I did not have the jcenter() Thank you!

If I may ask you a different question.
ContextCompat.checkSelfPermission(mActivity.get(), permission) always  returns PackageManager.PERMISSION_GRANTED 

Although the permission is not granted. Any ideas? 

I am usign a Nexus 5 API 23 AVD with Android 6.0 x86_64

**Comment by greysonp** [comment]
Can you tell me the constant of the permission you're requesting?

**Comment by biovolt** [comment]
I think I figured it out.
My android:targetSdkVersion was not 23 in my manifest.

Thank you for the help and sharing your project!

If you don't mind please add the 2 requirements 
jcenter() and targetSdkVersion to your instructions

This might help other people.

**Comment by greysonp** [comment]
Awesome! Quick question, did you have anything in `repositories {}`? If you had `mavenCentral` and it didn't work then that's a problem. Just want to make sure that's working. 

Otherwise, I'll update the readme soon.

Thanks!

**Comment by biovolt** [comment]
I had the following in my Project build.gradle file

allprojects {
    repositories {
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
    }

**Comment by greysonp** [comment]
Turns out that I misunderstood how bintray mavenCentral syncing worked. Thought it happened automatically, but turns out you have to click a button for each version :yum:  Fixed it! The new versions are all in the process of syncing to mavenCentral, so I won't have to update the readme about that, since both possible default repositories are covered now.

Thanks for helping me discover this!
